# Generated by Django 6.0.4 on 2026-09-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0010_alter_aluno_cpf'),
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='aulas', to='alunos.aluno'),
        ),
    ]
