# Generated by Django 6.0.4 on 2026-10-01 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0002_aula_alunos'),
        ('modalidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='modalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aulas', to='modalidades.modalidade'),
        ),
    ]
