# Generated by Django 6.0.4 on 2026-07-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0007_alter_aluno_faixa_jiujitsu_alter_aluno_faixa_judo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
