# Generated by Django 6.0.4 on 2026-07-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0008_aluno_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
