# Generated by Django 6.0.4 on 2026-10-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0010_alter_aluno_cpf'),
        ('modalidades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='modalidade',
        ),
        migrations.AddField(
            model_name='aluno',
            name='modalidades',
            field=models.ManyToManyField(blank=True, related_name='alunos', to='modalidades.modalidade'),
        ),
    ]
