# Generated by Django 6.0.4 on 2026-07-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competicoes',
            name='estado',
            field=models.CharField(max_length=2),
        ),
    ]
