# Generated by Django 6.0.4 on 2026-08-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicao', '0002_alter_competicoes_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='competicoes',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('ENCERRADA', 'Encerrada'), ('FINALIZADA', 'Finalizada')], default='ABERTA', max_length=20),
        ),
    ]
