# Generated by Django 6.0.4 on 2026-08-01 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0010_alter_aluno_cpf'),
        ('competicao', '0003_competicoes_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscricaoCompeticao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pago', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_competicao', to='alunos.aluno')),
                ('competicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='competicao.competicoes')),
            ],
        ),
    ]
