# Generated by Django 6.0.4 on 2026-08-04 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicao', '0004_inscricaocompeticao'),
        ('modalidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competicoes',
            name='modalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competicoes', to='modalidades.modalidade'),
        ),
    ]
