# Generated by Django 6.0.4 on 2026-09-28 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicao', '0005_competicoes_modalidade'),
        ('modalidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competicoes',
            name='modalidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='competicoes', to='modalidades.modalidade'),
            preserve_default=False,
        ),
    ]
